// const movieRating=8;
// if (movieRating>7) {
//     console.log("so bad")
// } else {
//     console.log("so good")
// }

// const movieBudget=666666666;
// if (movieBudget>=111111111&&movieBudget<=777777777) {
//     console.log("Big-budget-movie")
// } else {
//     console.log("Indie movie")
// }

// const movieGenre = "Horror";
// const audienceAge = 17;
// if (movieGenre === "Horror") {
//   if (audienceAge >= 18) {
//     console.log("Suitable for audience");
//   } else {
//     console.log("Not Suitable for audience");
//   }
// } else {
//   console.log("Suitable for all audience");
// }

// const firstMovieDuration = 120; // דוגמה למשך הסרט הראשון (בדקות)
// const secondMovieDuration = 90; // דוגמה למשך הסרט השני (בדקות)

// if (firstMovieDuration === secondMovieDuration) { //בדיקת שוויון
//   console.log("Movies have the same duration");  
// } else if (firstMovieDuration > secondMovieDuration) {
//     console.log("The first movies is longer");} 
//     else {
//   console.log("The second movies is longer");}

/*------------6-------------*/
// const popularityScore = 85; //השמת משתנה 
// const result=popularityScore>=80? "popular":"not popular";
// console.log(result);

/*------------6-------------*/
// const p_Score = 20;
// console.log(p_Score>=15?"yes":"not");

/*------------7------------- */
// const numberOfAwards=15;
// console.log(numberOfAwards%2===0?"Awards":"Not Awards") ;

/*------------8------------- */
// const ageOfPlayer=16;
// const result=ageOfPlayer<14?"Child":ageOfPlayer<=24?"Young":"Adult";
// console.log(result);
/*------------8------------- */

// const ageOfPlayer=16;
// console.log(ageOfPlayer<14?"Child":ageOfPlayer<=24?"Young":"Adult");

// /*---------9------------- */
// const HasInvitation = false;
// console.log(HasInvitation!=false ? "Welcome to the premiere" : "Please check your invitation");
// /*--------10------------- */
// const ScreeningDuration=121;
// console.log(ScreeningDuration<40? "Short":ScreeningDuration<=120? "Feuture":"Length")
/*-----------11------------- */

/*-----------12------------- */
/*-----------13------------- */
/*-----------14------------- */
/*-----------15------------- */


